name: Deploy Sphinx Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:

    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sphinx
        run: pip install sphinx

      - name: Build docs
        run: |
          cd docs
          .\make.bat html

      - name: Add .nojekyll
        run: touch docs/_build/html/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html